### ISSUE TITLE
Retrieved Graph Disconnected

### ISSUE THREAD

**Issue by philippkiesling** [ywnch/toolbox#5] opened 2020-10-03 09:57 UTC
Hi, first of all thank you for providing the toolbox!
I am trying to add Nodes(POIs) to the Graph and calculate the shortest path to them afterwards using the networkx shortest path (dijkstra) implementation. 

I am able  to reproduce the integrated supermarket plot at the end of the demo_connect_poi, but I am not able to calculate the shortest path, between them as the graph seems to be disconnected. 
So far I tried: 

- Overwriting Nans  in the 'from' and 'to'column with the corresponding u and v
- Only use Edges with the "from" and "to" column
- Set a very large number for threshold
- Ensure that the key is not equal to any of the osmid node ids

The output new_nodes however always contains nodes that are not in "u","v","from" or "to".... 

I am applying you function to a very large dataset with coordinates that may be very close to each other, maybe this is what is causing issues. 
Any help would be very appreciated! :)

My function call:
`
nodes, edges = connect_poi(pois, original_nodes, orriginal_edges, key_col = "osmid", threshold = 9990000000)
`
Verbose output of the connect_poi function: 

Building rtree...
Updating external nodes...
Projecting POIs to the network...
Updating internal nodes...
Updating internal edges...
Updating external links...
Remove faulty projections: 0/76555 (0.00%)
NOTE: duplication in node coordinates keys
Nodes count: 197932
Node coordinates key count: 60229
Missing 'from' nodes: 0
Missing 'to' nodes: 0

**Comment by VuokkoH** [comment] 2021-05-20 07:18
Hi! I also want to start by thanking for providing this tool, it's just simply awesome.

I ran into the same problem as @philippkiesling; `from` and `to` ids in `new_edges` related to splitted edges got messed up in the process.  Random/ negative osmids got introduced to the `new_edges` which causes the splitted edges to be disconnected from the network.  Geometry is ok, but osmid in `from`and `to` columns does not (always) match the associated node in `new_nodes`. 

My nodes dataframe had osmids outside the int32 range, which seems to be the root cause for this issue. For example, osmid `3186196878` got converted into a negative value. 

After quite a lot of testing & debugging, I narrowed down the issue to line 225 in `toolbox.py`; int-conversion doesn't handle osmids with too many digits;

I modified line 225: 
`nodes_id_dict = dict(zip(nodes_coord, nodes_meter['osmid'].astype(int)))`

as: 
`nodes_id_dict = dict(zip(nodes_coord, nodes_meter['osmid'].astype('Int64')))`

which fixes the issue.

**Comment by ywnch** [comment] 2021-06-01 14:41
Hi Vuokko, thanks a lot for debugging! I Will close this issue for now but I guess maybe a better fix is to decouple ID labeling (i.e., osmid) from the algorithm and allow user-defined ID labeling, which will also make the process more robust and flexible. Will try to find a time and iterate on this. Thanks again!

**Closed as completed by ywnch** 2021-06-01 14:41 UTC
